services:
  - type: web
    name: localai-test
    runtime: docker
    plan: free
    image:
      url: localai/localai:latest-aio-cpu
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /readyz